# -*- coding: utf-8 -*-
"""FACTORES PRIMOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tukOqOYTHWJYw9VzzuVDKiEtSE-YS7qd

PURPOSED BY adr

Obtener factores primos al descomponer un número.

Ejemplos:
----------------------------------
Descomponer 12

12|2
6 |2
3 |3
1 |

Obtener: 2,2,3
----------------------------------
Descomponer 8405

8405|5
1681|41
41 |41
1 |

Obtener: 5,41,41
"""

def calc(number, lista=[]):
  fac = [i for i in range(2,number+1) if number%i == 0]
  if number ==1:
    return lista
  else:
    lista.append(fac[0])
    ope = int(number/fac[0])
    calc(ope,lista)

lista = []
calc(8405,lista)
lista