# -*- coding: utf-8 -*-
"""NUMERO CURIOSO - VERSION ANTIGUA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b0KhkztK8GM5LwWYinQCFhwCSkynAZQY
"""

c = 9999  
d = 0  
l2 = []  
l3 = []  
l4 = []  
e = 0  
f = 0  
j = 0  
n = 0  
h = 0  
  
def ar (li,num):  
    e = 0  
    f = 0  
    while f < 5:  
        f = f + 1  
        e = num % 10  
        li.append(int(e))   
        num = num / 10  
  
def comp(liza,liz,cs):  
    j = 0  
    if liz[0] != liz [1] and liz[1] != liz[2] and liz[2] != liz[3] and liz[3] != liz[4]:  
        j = j + 1      
    if liz[0] != liz[2] and liz[0] != liz[3] and liz[0] != liz[4]:  
        j = j + 1  
    if liz[1] != liz[3] and liz[1] != liz[4]:  
        j = j + 1  
    if liz[2] != liz[4]:  
        j = j + 1  
  
    if j == 4:  
        liza.append(cs)  
        #print(l3)  
        del(liz[0:5])      
    else:  
        del(liz[0:5])  
  
def fin (ltr,lt):  
    n = 0  
    for g in lt:  
        for h in range(1):  
            if ((g - (7-1)) % 7 == 0) and ((g - (8-1)) % 8 == 0) and ((g - (9-1)) % 9 == 0):  
                if ((g - (10-1)) % 10 == 0) and ((g - (11-1)) % 11 == 0)and ((g - (12-1)) % 12 == 0):  
                    n = 5  
        if n == 5:  
            print("coo")  
            n = 0  
            ltr.append(g)  
            print(g)  
              
      
while c <= 99999:  
    c = c + 1  
    ar(l2,c)  
    comp(l3,l2,c)  
  
fin(l4,l3)      
print("!!EL Numero curioso es¡¡ ",l4)