# -*- coding: utf-8 -*-
"""NUMERO CURIOSO - Version Mejorada.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oY8otCMsW0utxVdBLrJgi_nvWnWpB0V1

PORPUSED BY "nRikee"

Este es un desafío matemático de la Real Sociedad Matemática Española. Y dice así:


El equipo que preparamos los desafíos matemáticos hemos decidido abonarnos durante todo el año a un número de la Lotería. Para elegir ese número, que debe estar comprendido entre el 0 y el 99.999, pusimos como condición que tuviese las cinco cifras distintas y que, además, cumpliese alguna otra propiedad interesante. Finalmente hemos conseguido un número que tiene la siguiente propiedad: si numeramos los meses del año del 1 al 12, en cualquier mes del año ocurre que al restar a nuestro número de lotería el número del mes anterior, el resultado es divisible por el número del mes en el que estemos. Y esto sucede para cada uno de los meses del año.

Es decir, si llamamos L a nuestro número, tenemos por ejemplo que en marzo L-2 es divisible entre 3 y en diciembre L-11 es divisible entre 12.

El reto que os planteamos es que nos digáis a qué número de Lotería estamos abonados.

Fuente
"""

def multiplo (numero):
  cont = 0
  for aux in range(1,13):
      if (numero - (aux-1))% aux == 0 :
        cont = cont + 1
        if(cont == 12):
          return "es"

def diferencia(lista,pos,flag ,increment = 0):

  for nume,valor in enumerate(lista):
    if pos != nume:
      if (lista[pos] == valor):
        flag = flag + 1  
  increment = increment + 1
  if(increment < 5 ):
    flag = diferencia(lista,increment,flag,increment)
  
  return flag

num = []
flag = 0
for p in range(10000,99999):
 
  for i in iter(str(p)):
    num.append(int(i))

  res=diferencia(num,0,flag)
  if(res == 0):   
    solucion = multiplo(p)
    if solucion == "es": 
      print("El numero Curioso es!!! ", p)
      break

  num = []