# -*- coding: utf-8 -*-
"""NUMEROS REPETIDOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16nkVNcu_Pwbf7h_RqD--JlCVlCc6fGrT

PURPOSED BY "sandrita"
programa en c que determine si un numero tiene digitos repetidos
"""

numero = 1111
digitos = []
digitos = [int(i) for i in iter(str(numero))]
simple = []
digitos
conteo = 0
conteo = comparar(digitos,conteo)
conteo

def comparar(listanumero,cont):
  conta = cont
  copia = []
  for i,v in enumerate(listanumero):
    for j,k in enumerate(listanumero):
      if i != j and listanumero[i] != "done":
        print ("comparando i: ", i , " con j " , j)
        if(v == k):
          print ("comparando v: ", v , " con k: " , k)
          conta = conta + 1
          copia.append(v)
          listanumero[i] = "done"

  return "se encontraron ", len(copia) , " numeros repetidos" , " valor de contador: " , conta