# -*- coding: utf-8 -*-
"""PRIMOS GEMELOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157GNsqjdMCltTpIJmbLhcCXHN6exDBW6

PURSOSED BY "Francisco Moises"
el usuario ingresa un numero positivo y el programa devuelve !! unicamente!! 
los primos gemelos menores al numero ingresado (necesito un solucion que sea un poco cencilla ) 
soy nuevo en c++ y quiero aprender gracias de antemano¡
"""

def numprimo(numero,limite):
  cont = 0
  for numero in range (limite+1):
    for j in range(1,numero+1):
      if (numero > 1 ):
        if(numero%j == 0):
          cont = cont + 1

    if(cont == 2):
      lista.append(numero)
    cont = 0
  return lista

numerolimite = 32
lista = [];listadef = []
primo = 0
lista = numprimo(primo,numerolimite)

for i,v in enumerate(lista):
  if v+2 in lista:
    listadef.append([[v,v+2]])    

print(listadef)