# -*- coding: utf-8 -*-
"""MIN AND SECOND MIN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11m8kQnyjGpSmR2B5jVCJ6FS3LFjHCqJn

PROPOSED BY "Fernando Pelliccioni"

Enunciado
Escribir la función

minelement1st_2nd(S)

que retorne el par de elementos (f, s) dado que f sea el menor elemento de la secuencia y s sea el segundo menor elemento de la secuencia.

Escribir la función en dos variantes. La primera es usando una Relación. La segunda variante usando la relación por defecto.

Escribirlo de la forma más eficiente posible, describiendo su complejidad en tiempo y espacio.

Relacionado con los desafíos:
http://www.solveet.com/exercises/Min-y-Max/244
http://www.solveet.com/exercises/Min-y-Max-de-una-secuencia/251
http://www.solveet.com/exercises/MinMax-de-una-secuencia/252
"""

import random
def minelement1st_2nd(S):
  S.sort()
  s=S[0];f=S[1]
  return s,f

list1 = [random.random()+1 for i in range(4)]#Creation of the list filling it with random numbers
#list1 = [99,400,1,222,45] #or we can jsut trype them

minelement1st_2nd(list1)